"""empty message

Revision ID: 1f458b2cc587
Revises: 53665954567d
Create Date: 2022-05-16 11:21:28.761416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f458b2cc587'
down_revision = '53665954567d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'bio')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.add_column('blogs', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
