"""empty message

Revision ID: 53665954567d
Revises: edd15c55ef9e
Create Date: 2022-05-16 10:49:20.550339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53665954567d'
down_revision = 'edd15c55ef9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'bio')
    # ### end Alembic commands ###
